import React from "react";
import { FileText, Download, Trash2, Plus, Calendar } from "lucide-react";
import { Card, CardHeader } from "@/components/common/Card";
import { Button } from "@/components/common/Button";
import { useAnalysisStore } from "@/store/analysisStore";
import { formatDate } from "@/utils/helpers";
import { jsPDF } from "jspdf";

const Reports: React.FC = () => {
  const { reports, removeReport, analyses } = useAnalysisStore();

  const downloadPdf = (report: any) => {
    const pdf = new jsPDF();
    pdf.setFont("Helvetica", "normal");

    pdf.setFontSize(16);
    pdf.text("Accreditation Evaluation Report", 20, 20);

    pdf.setFontSize(11);
    pdf.text(`Title: ${report.title}`, 20, 40);
    pdf.text(`Generated: ${formatDate(report.generatedAt)}`, 20, 50);
    pdf.text(
      `Overall Compliance: ${report.overallCompliance.toUpperCase()}`,
      20,
      60
    );

    pdf.setFontSize(10);
    pdf.text(
      "This report was generated by the DetEdTech platform for accreditation review.",
      20,
      80,
      { maxWidth: 170 }
    );

    pdf.save(`DetEdTech_Report_${Date.now()}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Evaluation Reports</h1>
          <p className="text-gray-500 mt-1">
            Download accreditation evaluation reports
          </p>
        </div>
        <Button icon={<Plus className="w-4 h-4" />}>Generate Report</Button>
      </div>

      <Card>
        <CardHeader
          title="Generated Reports"
          subtitle={`${reports.length} reports`}
        />

        {reports.length === 0 ? (
          <div className="text-center py-10 text-gray-500">
            No reports generated yet
          </div>
        ) : (
          <div className="space-y-4">
            {reports.map((report) => (
              <div
                key={report.id}
                className="flex items-center justify-between p-4 border rounded-lg"
              >
                <div className="flex items-center gap-4">
                  <FileText className="w-6 h-6 text-gray-400" />
                  <div>
                    <p className="font-medium">{report.title}</p>
                    <div className="flex items-center gap-2 text-sm text-gray-500">
                      <Calendar className="w-4 h-4" />
                      {formatDate(report.generatedAt)}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <Button
                    variant="secondary"
                    size="sm"
                    icon={<Download className="w-4 h-4" />}
                    onClick={() => downloadPdf(report)}
                  >
                    Download PDF
                  </Button>

                  <Button
                    variant="ghost"
                    size="sm"
                    icon={<Trash2 className="w-4 h-4 text-red-500" />}
                    onClick={() => removeReport(report.id)}
                  />
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>

      {analyses.length > 0 && (
        <Card>
          <CardHeader title="Analysis History" />
          <div className="space-y-3">
            {analyses.slice(0, 5).map((analysis) => (
              <div
                key={analysis.id}
                className="flex justify-between p-3 bg-gray-50 rounded"
              >
                <span>{formatDate(analysis.timestamp)}</span>
                <span className="text-sm">{analysis.overallStatus}</span>
              </div>
            ))}
          </div>
        </Card>
      )}
    </div>
  );
};

export default Reports;
