import { jsPDF } from "jspdf";

export function exportReportToPdf(report: {
  title: string;
  generatedAt: string | Date;
  overallCompliance: string;
}) {
  const doc = new jsPDF();

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(16);
  doc.text("Accreditation Evaluation Report", 20, 20);

  doc.setFontSize(11);
  doc.text(`Title: ${report.title}`, 20, 35);
  doc.text(
    `Generated: ${
      typeof report.generatedAt === "string"
        ? report.generatedAt
        : report.generatedAt.toLocaleDateString()
    }`,
    20,
    45
  );
  doc.text(
    `Overall compliance: ${report.overallCompliance.toUpperCase()}`,
    20,
    55
  );

  doc.setFontSize(10);
  doc.text(
    "This report was generated by the DetEdTech platform\nfor academic and accreditation review purposes.",
    20,
    75
  );

  doc.save(`DetEdTech_Report_${Date.now()}.pdf`);
}
